project/project/Scripts/daily_income_expense/accountapp/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',v.home),
    path('register',v.register_view,name='reg'),
    path('login',v.login_view,name='login'),
    path('logout',v.logout_view,name='logout'),

]

project/project/Scripts/daily_income_expense/daily_income_expense/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('accountapp.urls','accountapp'),namespace='accountapp')),
    path('',include(('incomeapp.urls','incomeapp'),namespace='incomeapp')),
    path('',include(('expenseapp.urls','expenseapp'),namespace='expenseapp')),
]

project/project/Scripts/daily_income_expense/expenseapp/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addexpense',v.add_expense,name='add'),
    path('exp_list',v.expense_list,name='list2'),
   # path('delete/<int:exid>',v.delete_l),
   # path('edit/<int:exid>',v.edit_l),
   path('expenseapp_search',v.exp_search,name='expenseapp_search'),
   path('ext/<str:ext2>',v.sort_by_expense_type,name='ext1'),
]

project/project/Scripts/daily_income_expense/incomeapp/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addincome',v.add_income,name='add'),
    path('inc_list',v.income_list,name='list1'),
    #path('delete/<int:icid>',v.delete_l),
    #path('edit/<int:icid>',v.edit_l),
    path('incomeapp_search',v.inc_search,name='incomeapp_search'),
    path('inct/<str:inct2>',v.sort_by_income_type,name='inct1'),

]

project/project/Scripts/daily_income_expense/accountapp/models.py
from django.db import models

# Create your models here.

from django import forms
class loginform(forms.Form):
    username=forms.CharField(max_length=30)
    password=forms.CharField(max_length=30,widget=forms.PasswordInput)

project/project/Scripts/daily_income_expense/expenseapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Expense(models.Model):
    expense=models.IntegerField()
    expense_type=models.CharField(max_length=30)
    expense_date=models.DateField(auto_now=True)
    description=models.TextField(max_length=300)
    user=models.ForeignKey(User,on_delete=models.CASCADE)


    class Meta:
        db_table='expense'

from django import forms
class ExpenseForm(forms.ModelForm):
    class Meta:
        model=Expense
        fields='__all__'

project/project/Scripts/daily_income_expense/incomeapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Income(models.Model):
    income=models.IntegerField()
    income_type=models.CharField(max_length=30)
    income_date=models.DateField()
    description=models.TextField(max_length=300)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        db_table='income'



from django import forms
class IncomeForm(forms.ModelForm):
    class Meta:
        model=Income
        fields='__all__'

project/project/Scripts/daily_income_expense/accountapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout

# Create your views here.

def home(request):
    context={'bal':get_balance(request)}
    return render(request,'home.html',context)


def register_view(request):
    if request.method=='POST':
        f=UserCreationForm(request.POST)
        f.save()
        return redirect('/')
    else:
        f=UserCreationForm
        context={'form':f}
 
        return render(request,'register.html',context)
    

from .models import loginform
def login_view(request):
    if request.method=='POST':
        uname=request.POST.get('username')    
        passw=request.POST.get('password')
        user=authenticate(request,username=uname,password=passw)

        if user is not None:
            request.session['uid']=user.id
            login(request,user)
            return redirect('/')
        else:
            f=loginform
            context={'form':f}
            return render(request,'login.html',context)  

    else:
        f=loginform
        context={'form':f}
        return render(request,'login.html',context)
    


def logout_view(request):
    logout(request)
    return redirect('/')



from incomeapp.models import Income
from expenseapp.models import Expense
def get_balance(request):
    uid=request.session.get('uid')
    incl=Income.objects.filter(user=uid)
    expl=Expense.objects.filter(user=uid)


    total_income=0
    total_expense=0

    for i in incl:
        total_income=total_income+i.income

    for i in expl:
        total_expense=total_expense+i.expense

    return total_income-total_expense

project/project/Scripts/daily_income_expense/accountapp/templates/addexpense.html
{%extends 'sidebar.html'%} {%block body%}

<h1>Please Add Expense Here</h1>

<form action='' method="post" >
    {%csrf_token%}
    <table border="1">
        <tr>
    <th><label for="id_expense">Expense:</label></th>
    <td>
      
      <input type="number" name="expense" required id="id_expense">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_expense_type">Expense type:</label></th>
    <td>
      
      <input type="text" name="expense_type" maxlength="30" required id="id_expense_type">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_description">Description:</label></th>
    <td>
      
      <textarea name="description" cols="40" rows="10" maxlength="300" required id="id_description">
</textarea>
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_user">User:</label></th>
    <td><input type="text" value="{{user}}"></td>
   
      
        
      
    
  </tr>
        <tr>
            <td><input type='submit' value='save'></td>
            <td><input type='reset' value='reset'></td>
        </tr>
    </table>
</form>
{%endblock%}

project/project/Scripts/daily_income_expense/accountapp/templates/addincome.html
{%extends 'sidebar.html'%} {%block body%}

<h1>Please Add Income Here</h1>

<form action='' method="post" >
    {%csrf_token%}
    <table border="1">
        <tr>
    <th><label for="id_income">Income:</label></th>
    <td>
      
      <input type="number" name="income" required id="id_income">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_income_type">Income type:</label></th>
    <td>
      
      <input type="text" name="income_type" maxlength="30" required id="id_income_type">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_income_date">Income date:</label></th>
    <td>
      
      <input type="text" name="income_date" required id="id_income_date">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_description">Description:</label></th>
    <td>
      
      <textarea name="description" cols="40" rows="10" maxlength="300" required id="id_description">
</textarea>
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_user">User:</label></th>
    <td><input type='text' value='{{user}}'></td>
  </tr>
      
    

  


      
      
        
      
    
  
        <tr>
            <td><input type='submit' value='save'></td>
            <td><input type='reset' value='reset'></td>
        </tr>
    </table>
    
</form>

{%endblock%}

project/project/Scripts/daily_income_expense/accountapp/templates/expenselist.html
{%extends 'sidebar.html'%} {%block body%}

<h1>Expense List</h1>

<form action="{%url 'expenseapp:expenseapp_search'%}" method="post">
    {%csrf_token%}
    <textarea name="srch" id="" rows="3" cols="60"></textarea>
    <input type="submit" value="search">
</form>
{%if expl%}
<table border="1">
    <tr>
        <th>Id</th>
        <th>Expense</th>
        <th>Expense_type</th>
        <th>Expense_date</th>
        <th>Description</th>
        <th>User</th>
        <th colspan='3'>Action</th>

    </tr>
    
    {%for i in expl%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.expense}}</td>
        <td>{{i.expense_type}}</td>
        <td>{{i.expense_date}}</td>
        <td>{{i.description}}</td>
        <td>{{i.user}}</td>
        <td><a href="delete/{{i.id}}">Delete</a></td>
        <td><a href="edit/{{i.id}}">Edit</a></td>
    </tr>
    {%endfor%}

</table>
{%else%}
<h1>No Record Found...</h1>
{%endif%}
<style>
    .rside{
        width:200px;
        height:100%;
        background-color: aquamarine;
        position:fixed;
        right:0%;
        top:0%
    }
    h3{
        margin:10px;
        padding:10px;
    }
    .rside a{
        text-decoration: none;
    }
</style>
<div class="rside">

    <h2>Sort by expense_type</h2>
    <h3><a href="{%url 'expenseapp:list2'%}"> All</a></h3>
    {%for i in expt%}
    <h3><a href="{%url 'expenseapp:ext1' i%}">{{i}}</a></h3>
    {%endfor%}
</div>





{%endblock%}

project/project/Scripts/daily_income_expense/accountapp/templates/home.html
{%extends 'sidebar.html'%} {%block body%}

<h1>Daily Income Expense Project</h1>
{%if user.is_authenticated%}
<h2 style="color:royalblue;">Welcome:{{user}}</h2>
<h2 style="color:brown;">Total balance is:{{bal}}</h2>
{%endif%}
{%endblock%}

project/project/Scripts/daily_income_expense/accountapp/templates/incomelist.html
{%extends 'sidebar.html'%} {%block body%}

<h1>All Income List</h1>

<form action="{%url 'incomeapp:incomeapp_search'%}" method="post">
    {%csrf_token%}
    <textarea name="srch" id="" rows="3" cols="60"></textarea>
    <input type="submit" value="search">
</form>

{%if incl%}


<table border="1">
    <tr>
        <th>Id</th>
        <th>Income</th>
        <th>Income_type</th>
        <th>Income_date</th>
        <th>Description</th>
        <th>User</th>
        <th colspan='3'>Action</th>

    </tr>
    {%for i in incl%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.income}}</td>
        <td>{{i.income_type}}</td>
        <td>{{i.income_date}}</td>
        <td>{{i.description}}</td>
        <td>{{i.user}}</td>
        <td><a href='delete/{{i.id}}'>Delete</a></td>
        <td><a href='edit/{{i.id}}'>Edit</a></td>
    </tr>
    {%endfor%}
</table>
{%else%}
<h1>No Record Found...</h1>
{%endif%}

<style>
    .rside{
        width:200px;
        height:100%;
        background-color: aquamarine;
        position:fixed;
        right:0%;
        top:0%
    }
    h3{
        margin:10px;
        padding:10px;
    }
    .rside a{
        text-decoration: none;
    }
</style>
<div class="rside">

    <h2>Sort by income_type</h2>
    <h3><a href="{%url 'incomeapp:list1'%}"> All</a></h3>
    {%for i in inct%}
    <h3><a href="{%url 'incomeapp:inct1' i%}">{{i}}</a></h3>
    {%endfor%}
</div>



{%endblock%}

project/project/Scripts/daily_income_expense/accountapp/templates/login.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>Login Form</h1>

<form action="" method="post">
    {%csrf_token%}
    <table>
        {{form.as_table}}
        <tr>
            <td><input type='submit' value='login'></td>
        </tr>
    </table>
</form>

{%endblock%}

project/project/Scripts/daily_income_expense/accountapp/templates/register.html
{%extends 'sidebar.html'%} {%block body%}

<h1>Registration Form</h1>

<form action='' method="post" >
    {%csrf_token%}
    <table border="1">
        {{form.as_table}}
        <tr>
            <td><input type='submit' value='save'></td>
            <td><input type='reset' value='reset'></td>
        </tr>
    </table>
</form>

{%endblock%}

project/project/Scripts/daily_income_expense/accountapp/templates/sidebar.html
{%load static%}
<link rel="stylesheet" href="{%static 'css/style.css'%}" />
<div class="side">
    {%if user.is_authenticated%}

    <h2><a href="{%url 'incomeapp:add'%}">AddIncome</a></h2>
    <h2><a href="{%url 'expenseapp:add'%}">AddExpense</a></h2>
    <h2><a href="{%url 'incomeapp:list1'%}">IncomeList</a></h2>
    <h2><a href="{%url 'expenseapp:list2'%}">ExpenseList</a></h2>
    <h2><a href="{%url 'accountapp:logout'%}">Logout</a></h2>
    <h2><a href="">Edit_Profile</a></h2>
    {%else%}
    <h2><a href="{%url 'accountapp:reg'%}">Register</a><br/></h2>

    <h2><a href="{%url 'accountapp:login'%}">Login</a></h2>
    {%endif%}
    <h2><a href="/">Home</a></h2>
    <h2><a href="">About_Us</a></h2>

</div>

<div class="main"> {%block body%} {%endblock%}</div>